import { NextResponse } from 'next/server';
import { adminClient } from '@/lib/sanity-admin';

export async function POST() {
  try {
    // Step 1: Delete ALL existing product pages to clean up duplicates
    console.log('Cleaning up old product pages...');
    const oldPages = await adminClient.fetch(
      `*[_type == "page" && (
        slug.current match "sidekick*" ||
        slug.current match "*sidekick*" ||
        slug.current match "customer-ai*" ||
        slug.current match "*customer-ai*" ||
        slug.current match "guides*" ||
        slug.current match "*guides*" ||
        slug.current match "app-platform*" ||
        slug.current match "*app-platform*"
      )]{_id}`
    );

    for (const page of oldPages) {
      await adminClient.delete(page._id);
      console.log(`Deleted: ${page._id}`);
    }

    // Step 2: Create ALL 7 products with complete content
    const products = [
      {
        _type: 'page',
        _id: 'page-product-sidekick-standalone',
        title: 'Sidekick Standalone',
        slug: { _type: 'slug', current: 'sidekick-standalone' },
        quickNav: [
          { label: 'Overview', anchor: 'overview' },
          { label: 'Platforms', anchor: 'platforms' },
          { label: 'Use Cases', anchor: 'use-cases' },
          { label: 'Content', anchor: 'content' },
          { label: 'Demos', anchor: 'demos' },
          { label: 'Competitive', anchor: 'competitive' },
        ],
        pageBuilder: [
          {
            _type: 'heroSection',
            _key: 'hero',
            badge: 'SIDEKICK STANDALONE',
            heading: 'AI That Works With Your Helpdesk',
            subheading: 'Integrate Sidekick AI with Zendesk, Salesforce, Kustomer, or any existing platform to automate customer support',
            layout: '2-column',
            videoMediaId: 'mwar81dg26',
            primaryCtaText: 'Learn More',
            primaryCtaLink: '#overview',
            secondaryCtaText: 'View Demos',
            secondaryCtaLink: '#demos',
            backgroundColor: 'green',
          },
          {
            _type: 'contentSection',
            _key: 'overview',
            anchorId: 'overview',
            sectionTitle: 'What is Sidekick Standalone?',
            backgroundColor: 'dark',
            includeLaunchStatus: true,
            launchStatus: {
              heading: '🚀 Launch Status',
              statusItems: [
                { label: 'Initial research', isActive: false },
                { label: 'Added to roadmap', isActive: false },
                { label: 'Discovery and design', isActive: false },
                { label: 'Build in progress', isActive: false },
                { label: '➡️ Prototyping ⬅️', isActive: true },
                { label: 'Limited rollout', isActive: false },
                { label: 'Broader rollout', isActive: false },
                { label: 'Open Access', isActive: false },
              ],
              description: 'Working version available internally. Early demos and testing happening with trusted customers.',
            },
            content: [
              {
                _type: 'block',
                children: [{ _type: 'span', text: 'Sidekick Standalone is an AI agent that integrates with your existing helpdesk platform to automate customer support inquiries. It works alongside your current setup—whether you use Zendesk, Salesforce Service Cloud, Kustomer, or another platform.' }],
              },
              {
                _type: 'block',
                children: [{ _type: 'span', text: 'Unlike other AI solutions that require you to replace your entire tech stack, Sidekick Standalone plugs into what you already have and starts resolving customer inquiries on day one.' }],
              },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'platforms',
            anchorId: 'platforms',
            sectionTitle: 'Works With Your Platform',
            backgroundColor: 'gray',
            columns: 3,
            features: [
              { icon: '🎫', title: 'Zendesk', description: 'Native integration with Zendesk Support and Sunshine Conversations' },
              { icon: '☁️', title: 'Salesforce', description: 'Works with Service Cloud and Einstein Bot' },
              { icon: '🔧', title: 'Kustomer', description: 'Seamless integration with Kustomer CRM' },
              { icon: '💬', title: 'Intercom', description: 'Connect Sidekick to Intercom messenger' },
              { icon: '🌱', title: 'Freshdesk', description: 'Integration with Freshworks products' },
              { icon: '🔌', title: 'Other Platforms', description: 'Custom integrations available via API' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'use-cases',
            anchorId: 'use-cases',
            sectionTitle: 'Common Use Cases',
            backgroundColor: 'white',
            columns: 2,
            variant: 'bordered',
            features: [
              { title: 'Where Is My Order (WISMO)', description: 'Automate order status inquiries with real-time tracking updates' },
              { title: 'Returns & Exchanges', description: 'Handle return requests, generate labels, and process exchanges' },
              { title: 'Account Management', description: 'Password resets, profile updates, subscription changes' },
              { title: 'Product Recommendations', description: 'Suggest products based on customer history and preferences' },
              { title: 'FAQs & Self-Service', description: 'Answer common questions about policies, shipping, products' },
              { title: 'Appointment Scheduling', description: 'Book, reschedule, and cancel appointments automatically' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'content',
            anchorId: 'content',
            sectionTitle: 'Content & Resources',
            backgroundColor: 'gray',
            columns: 3,
            variant: 'card',
            features: [
              { icon: '📄', title: 'One-Pagers', description: 'Quick product overviews and value propositions' },
              { icon: '📊', title: 'Presentation Decks', description: 'Full product decks and platform-specific presentations' },
              { icon: '⭐', title: 'Case Studies', description: 'Customer success stories by industry and use case' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'demos',
            anchorId: 'demos',
            sectionTitle: 'Demo Materials',
            backgroundColor: 'white',
            columns: 2,
            variant: 'card',
            features: [
              { icon: '💻', title: 'Demo Environments', description: 'Access live Sidekick demo environments with sample data' },
              { icon: '📝', title: 'Demo Scripts & Mockups', description: 'Conversation scripts and visual mockups for walkthroughs' },
              { icon: '🎥', title: 'Video Library', description: 'Product walkthrough videos and recorded demos' },
              { icon: '💰', title: 'ROI Calculator', description: 'Calculate cost savings and efficiency gains' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'competitive',
            anchorId: 'competitive',
            sectionTitle: 'Competitive Intelligence',
            backgroundColor: 'gray',
            columns: 3,
            variant: 'card',
            features: [
              { icon: '⚔️', title: 'Battle Cards', description: 'Positioning against Zendesk AI, Einstein, and other competitors' },
              { icon: '🔄', title: 'Migration Stories', description: 'Customer success stories from competitive replacements' },
              { icon: '💬', title: 'Objection Handling', description: 'Responses to common competitive objections' },
            ],
          },
          {
            _type: 'ctaSection',
            _key: 'cta',
            heading: 'Need Help With Sidekick?',
            description: 'Can\'t find what you\'re looking for? Reach out to the enablement team',
            primaryCtaText: 'Ask in #enablement-resources',
            primaryCtaLink: '#',
            secondaryCtaText: 'Browse All Products',
            secondaryCtaLink: '#',
            backgroundColor: 'purple',
          },
        ],
      },
      {
        _type: 'page',
        _id: 'page-product-sidekick-voice',
        title: 'Sidekick Voice',
        slug: { _type: 'slug', current: 'sidekick-voice' },
        quickNav: [
          { label: 'Overview', anchor: 'overview' },
          { label: 'Capabilities', anchor: 'capabilities' },
          { label: 'Use Cases', anchor: 'use-cases' },
          { label: 'Content', anchor: 'content' },
          { label: 'Demos', anchor: 'demos' },
          { label: 'Competitive', anchor: 'competitive' },
        ],
        pageBuilder: [
          {
            _type: 'heroSection',
            _key: 'hero',
            badge: 'SIDEKICK VOICE',
            heading: 'AI-Powered Voice Agent',
            subheading: 'Handle phone calls 24/7 with natural conversation AI that resolves customer inquiries instantly',
            layout: '2-column',
            videoMediaId: '62ev998jm3',
            videoAspectRatio: 1.7843866171003717,
            primaryCtaText: 'Learn More',
            primaryCtaLink: '#overview',
            secondaryCtaText: 'Hear Examples',
            secondaryCtaLink: '#demos',
            backgroundColor: 'green',
          },
          {
            _type: 'contentSection',
            _key: 'overview',
            anchorId: 'overview',
            sectionTitle: 'What is Sidekick Voice?',
            backgroundColor: 'dark',
            includeLaunchStatus: true,
            launchStatus: {
              heading: '🚀 Launch Status',
              statusItems: [
                { label: 'Initial research', isActive: false },
                { label: 'Added to roadmap', isActive: false },
                { label: 'Discovery and design', isActive: false },
                { label: 'Build in progress', isActive: false },
                { label: 'Prototyping', isActive: false },
                { label: '➡️ Limited rollout ⬅️', isActive: true },
                { label: 'Broader rollout', isActive: false },
                { label: 'Open Access', isActive: false },
              ],
              description: 'Beta available to select customers. Gathering feedback and optimizing performance.',
            },
            content: [
              {
                _type: 'block',
                children: [{ _type: 'span', text: 'Sidekick Voice is an AI phone agent that handles customer calls with natural, human-like conversation. It understands context, accesses customer data, and resolves inquiries without human intervention.' }],
              },
              {
                _type: 'block',
                children: [{ _type: 'span', text: 'Built on Gladly\'s Customer AI, Sidekick Voice seamlessly integrates with your existing phone system and knowledge base to provide instant, accurate responses 24/7.' }],
              },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'capabilities',
            anchorId: 'capabilities',
            sectionTitle: 'Voice Capabilities',
            backgroundColor: 'gray',
            columns: 3,
            variant: 'card',
            features: [
              { icon: '🗣️', title: 'Natural Conversation', description: 'Human-like dialogue with context awareness and interruption handling' },
              { icon: '🌐', title: 'Multi-Language Support', description: 'Handles calls in multiple languages with native fluency' },
              { icon: '🔄', title: 'Seamless Handoff', description: 'Intelligent routing to human agents when needed' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'use-cases',
            anchorId: 'use-cases',
            sectionTitle: 'Common Use Cases',
            backgroundColor: 'white',
            columns: 2,
            variant: 'bordered',
            features: [
              { title: 'Order Status Inquiries', description: 'Handle WISMO calls with real-time order tracking information' },
              { title: 'Appointment Scheduling', description: 'Book, reschedule, and cancel appointments via phone' },
              { title: 'Account Support', description: 'Password resets, balance inquiries, and account updates' },
              { title: 'Technical Support', description: 'Troubleshooting and resolution for common issues' },
              { title: 'After-Hours Support', description: '24/7 availability without staffing overnight shifts' },
              { title: 'Peak Volume Management', description: 'Scale instantly during high-volume periods' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'content',
            anchorId: 'content',
            sectionTitle: 'Content & Resources',
            backgroundColor: 'gray',
            columns: 3,
            variant: 'card',
            features: [
              { icon: '📄', title: 'Voice One-Pager', description: 'Quick overview of Sidekick Voice capabilities' },
              { icon: '📊', title: 'Voice ROI Calculator', description: 'Calculate savings from automating phone support' },
              { icon: '🎯', title: 'Implementation Guide', description: 'Step-by-step guide to deploying Voice' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'demos',
            anchorId: 'demos',
            sectionTitle: 'Demo Materials',
            backgroundColor: 'white',
            columns: 2,
            variant: 'card',
            features: [
              { icon: '🎧', title: 'Call Recordings Library', description: 'Real examples of Sidekick Voice handling customer calls' },
              { icon: '📱', title: 'Live Demo Number', description: 'Call our demo line to experience Sidekick Voice' },
              { icon: '🎬', title: 'Voice Demo Video', description: 'See Sidekick Voice in action with real scenarios' },
              { icon: '📝', title: 'Call Flow Templates', description: 'Example conversation flows for different use cases' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'competitive',
            anchorId: 'competitive',
            sectionTitle: 'Competitive Intelligence',
            backgroundColor: 'gray',
            columns: 3,
            variant: 'card',
            features: [
              { icon: '⚔️', title: 'Voice AI Comparison', description: 'How we compare to other voice AI solutions' },
              { icon: '🏆', title: 'Differentiators', description: 'What makes Sidekick Voice unique' },
              { icon: '💬', title: 'Objection Handling', description: 'Common concerns and responses' },
            ],
          },
          {
            _type: 'ctaSection',
            _key: 'cta',
            heading: 'Ready to See Sidekick Voice?',
            description: 'Experience our AI voice agent with a personalized demo',
            primaryCtaText: 'Schedule Demo',
            primaryCtaLink: '#',
            secondaryCtaText: 'Call Demo Line',
            secondaryCtaLink: '#',
            backgroundColor: 'purple',
          },
        ],
      },
      {
        _type: 'page',
        _id: 'page-product-sidekick-email',
        title: 'Sidekick Email',
        slug: { _type: 'slug', current: 'sidekick-email' },
        quickNav: [
          { label: 'What it is', anchor: 'what-it-is' },
          { label: 'Customer Trackers', anchor: 'customer-trackers' },
          { label: 'Content', anchor: 'content' },
          { label: 'Enablement', anchor: 'enablement' },
        ],
        pageBuilder: [
          {
            _type: 'heroSection',
            _key: 'hero',
            badge: 'SIDEKICK EMAIL',
            heading: 'Sidekick Email',
            subheading: 'Sidekick Email brings generative AI to email support, resolving issues directly in the inbox through AI-powered contextual responses that feel human and relevant. It works with Guides and integrations to answer questions and take actions.',
            layout: '2-column',
            videoMediaId: '62ev998jm3',
            videoAspectRatio: 1.7843866171003717,
            primaryCtaText: 'Learn More',
            primaryCtaLink: '#what-it-is',
            secondaryCtaText: 'View Resources',
            secondaryCtaLink: '#content',
            backgroundColor: 'green',
          },
          {
            _type: 'contentSection',
            _key: 'what-it-is',
            anchorId: 'what-it-is',
            sectionTitle: 'What it is',
            backgroundColor: 'dark',
            includeLaunchStatus: true,
            launchStatus: {
              heading: '🚀 Launch Status',
              statusItems: [
                { label: 'Initial research', isActive: false },
                { label: 'Added to roadmap', isActive: false },
                { label: 'Discovery and design', isActive: false },
                { label: 'Build in progress', isActive: false },
                { label: 'Prototyping', isActive: false },
                { label: '➡️ Limited rollout ⬅️', isActive: true },
                { label: 'Broader rollout', isActive: false },
                { label: 'Open Access', isActive: false },
              ],
              description: 'Sidekick Email is in limited rollout with select customers.',
            },
            content: [
              {
                _key: 'block-1',
                _type: 'block',
                children: [{ _key: 'span-1', _type: 'span', text: 'Sidekick Email brings generative AI to email support, resolving issues directly in the inbox through AI-powered contextual responses that feel human and relevant. It works with Guides and integrations to answer questions and take actions.' }],
              },
              {
                _key: 'block-2',
                _type: 'block',
                children: [{ _key: 'span-2', _type: 'span', text: 'Why it matters: Email is a top support channel, but emails are often long, unstructured, and difficult to parse, leading to slow responses and backlogs. Sidekick Email provides instant service with quick, accurate responses, reducing backlogs and supporting agents with handoff summaries, improving customer trust and hero productivity.', marks: ['strong'] }],
              },
              {
                _key: 'block-3',
                _type: 'block',
                children: [{ _key: 'span-3', _type: 'span', text: 'Who it\'s for: B2C Businesses that handle high volumes of email support, especially those with simple routing, high first contact resolution rates (FCR), and who are early adopters.', marks: ['strong'] }],
              },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'capabilities',
            sectionTitle: 'Key Capabilities',
            backgroundColor: 'dark',
            columns: 2,
            features: [
              { icon: '💬', title: 'AI-powered contextual responses', description: 'Delivers human-like, relevant email replies automatically' },
              { icon: '✅', title: 'Answers questions and takes actions', description: 'Not just responses—completes tasks and resolves issues' },
              { icon: '🔗', title: 'Works with Guides and integrations', description: 'Leverages existing workflows and connected systems' },
              { icon: '📧', title: 'Reduces backlogs', description: 'Handles high volume email efficiently at scale' },
              { icon: '👥', title: 'Supports heroes with handoff summaries', description: 'Provides context when escalation to agents is needed' },
              { icon: '⚡', title: 'Instant service delivery', description: 'Eliminates wait times for email responses' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'customer-trackers',
            anchorId: 'customer-trackers',
            sectionTitle: 'Customer Trackers',
            backgroundColor: 'white',
            columns: 3,
            features: [
              { icon: '📊', title: 'Customer Interest Tracker', description: 'Track customer interest and engagement with Sidekick Email' },
              { icon: '📱', title: 'List of available apps', description: 'Compatible applications and integrations' },
              { icon: '📈', title: 'SFDC Report', description: 'Salesforce reporting and analytics' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'content',
            anchorId: 'content',
            sectionTitle: 'Content',
            backgroundColor: 'gray',
            columns: 3,
            features: [
              { icon: '📄', title: 'Sidekick Email', description: 'Core product documentation and overview' },
              { icon: '📊', title: 'Intro Deck Sidekick Email', description: 'Introduction presentation for customer conversations' },
              { icon: '📝', title: 'Email How It Works One Pager', description: 'Quick reference guide explaining functionality' },
              { icon: '🔧', title: 'Sidekick Email Implementation', description: 'Implementation guide and best practices' },
              { icon: '📋', title: 'Email Generic One Pager', description: 'General overview one-pager for prospects' },
              { icon: '✉️', title: 'Follow Up Template', description: 'Email templates for follow-up communications' },
              { icon: '📬', title: 'Sidekick Email Follow-Up', description: 'Follow-up strategy and messaging guide' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'enablement',
            anchorId: 'enablement',
            sectionTitle: 'Enablement',
            backgroundColor: 'white',
            columns: 2,
            features: [
              { icon: '🎓', title: 'Sidekick Email + App Platform', description: 'Integration training with App Platform' },
              { icon: '📹', title: '6/18/25: SK for Email + App Enablement', description: 'Product enablement session recording' },
              { icon: '📚', title: 'Foundational Enablement For SK Email', description: 'Core training materials for Sidekick Email' },
              { icon: '❓', title: 'GTM FAQs | Q2 launch', description: 'Go-to-market frequently asked questions' },
              { icon: '📖', title: 'FAQ Doc', description: 'Comprehensive FAQ documentation' },
            ],
          },
          {
            _type: 'ctaSection',
            _key: 'cta',
            heading: 'Need Help With Sidekick Email?',
            subheading: 'Can\'t find what you\'re looking for? Reach out to the enablement team',
            primaryCtaText: 'Ask in #enablement-resources',
            primaryCtaLink: '#',
            secondaryCtaText: 'Browse All Products',
            secondaryCtaLink: '/product',
            backgroundColor: 'purple',
          },
        ],
      },
      {
        _type: 'page',
        _id: 'page-product-sidekick-sales',
        title: 'Sidekick Sales',
        slug: { _type: 'slug', current: 'sidekick-sales' },
        quickNav: [
          { label: 'Overview', anchor: 'overview' },
          { label: 'Capabilities', anchor: 'capabilities' },
          { label: 'Use Cases', anchor: 'use-cases' },
          { label: 'Content', anchor: 'content' },
          { label: 'Demos', anchor: 'demos' },
          { label: 'Competitive', anchor: 'competitive' },
        ],
        pageBuilder: [
          {
            _type: 'heroSection',
            _key: 'hero',
            badge: 'SIDEKICK SALES',
            heading: 'AI for Revenue Teams',
            subheading: 'Empower sales and marketing with AI that engages prospects, qualifies leads, and drives revenue',
            layout: '2-column',
            videoMediaId: '85i16s6k7a',
            videoAspectRatio: 1.7777777777777777,
            primaryCtaText: 'Learn More',
            primaryCtaLink: '#overview',
            secondaryCtaText: 'View Demos',
            secondaryCtaLink: '#demos',
            backgroundColor: 'green',
          },
          {
            _type: 'contentSection',
            _key: 'overview',
            anchorId: 'overview',
            sectionTitle: 'What is Sidekick Sales?',
            backgroundColor: 'dark',
            includeLaunchStatus: true,
            launchStatus: {
              heading: '🚀 Launch Status',
              statusItems: [
                { label: 'Initial research', isActive: false },
                { label: 'Added to roadmap', isActive: false },
                { label: '➡️ Discovery and design ⬅️', isActive: true },
                { label: 'Build in progress', isActive: false },
                { label: 'Prototyping', isActive: false },
                { label: 'Limited rollout', isActive: false },
                { label: 'Broader rollout', isActive: false },
                { label: 'Open Access', isActive: false },
              ],
              description: 'Product design phase. Gathering customer feedback on requirements and use cases.',
            },
            content: [
              {
                _key: 'block-1',
                _type: 'block',
                children: [{ _key: 'span-1', _type: 'span', text: 'Sidekick Sales is AI designed specifically for revenue generation. It engages website visitors, qualifies leads, books meetings, and nurtures prospects through the sales funnel.' }],
              },
              {
                _key: 'block-2',
                _type: 'block',
                children: [{ _key: 'span-2', _type: 'span', text: 'Unlike traditional chatbots that deflect, Sidekick Sales actively converts visitors into qualified opportunities and drives measurable revenue impact.' }],
              },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'capabilities',
            anchorId: 'capabilities',
            sectionTitle: 'Sales AI Capabilities',
            backgroundColor: 'gray',
            columns: 3,
            features: [
              { icon: '🎯', title: 'Lead Qualification', description: 'Automatically qualify prospects based on your ideal customer profile' },
              { icon: '📅', title: 'Meeting Scheduling', description: 'Book demos directly into AE calendars without back-and-forth' },
              { icon: '📈', title: 'Lead Nurturing', description: 'Engage prospects with personalized follow-ups and content' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'use-cases',
            anchorId: 'use-cases',
            sectionTitle: 'Common Use Cases',
            backgroundColor: 'white',
            columns: 2,
            features: [
              { icon: '🌐', title: 'Website Conversion', description: 'Convert anonymous visitors into qualified leads 24/7' },
              { icon: '📋', title: 'Demo Requests', description: 'Qualify and book product demos automatically' },
              { icon: '🎤', title: 'Event Follow-up', description: 'Engage trade show and webinar leads at scale' },
              { icon: '💰', title: 'Pricing Inquiries', description: 'Provide custom pricing based on prospect needs' },
              { icon: '📚', title: 'Content Recommendations', description: 'Share relevant case studies and resources' },
              { icon: '⚡', title: 'Pipeline Acceleration', description: 'Re-engage stalled deals and dormant accounts' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'content',
            anchorId: 'content',
            sectionTitle: 'Content & Resources',
            backgroundColor: 'gray',
            columns: 3,
            features: [
              { icon: '📄', title: 'Sales One-Pager', description: 'Quick overview for revenue teams' },
              { icon: '💰', title: 'Revenue Impact Calculator', description: 'Calculate potential pipeline and revenue lift' },
              { icon: '📚', title: 'Best Practices Guide', description: 'Optimize AI for maximum conversion' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'demos',
            anchorId: 'demos',
            sectionTitle: 'Demo Materials',
            backgroundColor: 'white',
            columns: 2,
            features: [
              { icon: '💻', title: 'Interactive Demo', description: 'Experience Sidekick Sales on a live website' },
              { icon: '📊', title: 'Performance Metrics', description: 'Real customer results and conversion rates' },
              { icon: '🎬', title: 'Customer Success Stories', description: 'Video testimonials from revenue teams' },
              { icon: '🔧', title: 'Integration Guides', description: 'Connect with CRM, marketing automation, and calendaring' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'competitive',
            anchorId: 'competitive',
            sectionTitle: 'Competitive Intelligence',
            backgroundColor: 'gray',
            columns: 3,
            features: [
              { icon: '⚔️', title: 'vs. Traditional Chatbots', description: 'Why Sidekick Sales converts better' },
              { icon: '🏆', title: 'Unique Differentiators', description: 'What sets us apart in the market' },
              { icon: '💬', title: 'Objection Handling', description: 'Address common sales concerns' },
            ],
          },
          {
            _type: 'ctaSection',
            _key: 'cta',
            heading: 'Ready to Drive More Revenue?',
            subheading: 'See how Sidekick Sales can transform your pipeline',
            primaryCtaText: 'Schedule Demo',
            primaryCtaLink: '#',
            secondaryCtaText: 'Calculate ROI',
            secondaryCtaLink: '#',
            backgroundColor: 'purple',
          },
        ],
      },
      {
        _type: 'page',
        _id: 'page-product-customer-ai',
        title: 'Gladly Customer AI',
        slug: { _type: 'slug', current: 'customer-ai' },
        quickNav: [
          { label: 'What it is', anchor: 'what-it-is' },
          { label: 'Quick Links for Sales', anchor: 'quick-links-sales' },
          { label: 'Quick Links for CS/AM', anchor: 'quick-links-csam' },
          { label: 'Customer AI Videos', anchor: 'videos' },
          { label: 'Shareable Content', anchor: 'shareable' },
          { label: 'PR', anchor: 'pr' },
          { label: 'Enablement', anchor: 'enablement' },
        ],
        pageBuilder: [
          {
            _type: 'heroSection',
            _key: 'hero',
            badge: 'CUSTOMER AI',
            heading: 'Gladly Customer AI',
            subheading: 'Gladly is Customer AI—the per-user intelligence layer that makes radically efficient, radically personal customer experiences possible, allowing AI to understand customers, predict needs, and teams through AI-powered customer intelligence.',
            layout: '2-column',
            primaryCtaText: 'Learn More',
            primaryCtaLink: '#what-it-is',
            secondaryCtaText: 'View Resources',
            secondaryCtaLink: '#shareable',
            backgroundColor: 'green',
          },
          {
            _type: 'contentSection',
            _key: 'what-it-is',
            anchorId: 'what-it-is',
            sectionTitle: 'What is Gladly?',
            backgroundColor: 'dark',
            includeLaunchStatus: true,
            launchStatus: {
              heading: '🚀 Launch Status',
              statusItems: [
                { label: 'Initial research', isActive: false },
                { label: 'Added to roadmap', isActive: false },
                { label: 'Discovery and design', isActive: false },
                { label: 'Build in progress', isActive: false },
                { label: 'Prototyping', isActive: false },
                { label: 'Limited rollout', isActive: false },
                { label: 'Broader rollout', isActive: false },
                { label: '➡️ Open Access 🎉 ⬅️', isActive: true },
              ],
              description: 'Customer AI is the foundational intelligence layer powering all Gladly products and is available to all customers.',
            },
            content: [
              {
                _key: 'block-1',
                _type: 'block',
                children: [{ _key: 'span-1', _type: 'span', text: 'Gladly is Customer AI—a per-user intelligence layer that makes radically efficient, radically personal experiences possible, allowing AI agents and human teams to understand customers, predict needs, and provide a seamless experience. It unifies customer conversations, commerce, AI, and support teams through AI-powered customer intelligence.' }],
              },
              {
                _key: 'block-2',
                _type: 'block',
                children: [{ _key: 'span-2', _type: 'span', text: 'Why it matters: Most platforms treat customer data as isolated tickets rather than continuous relationships. Gladly\'s Customer AI creates a persistent intelligence layer that powers all interactions, enabling both AI agents and human teams to deliver personalized service at scale with full customer context.', marks: ['strong'] }],
              },
              {
                _key: 'block-3',
                _type: 'block',
                children: [{ _key: 'span-3', _type: 'span', text: 'Who it\'s for: B2C Businesses with high-touch customer relationships, ecommerce platforms, and brands prioritizing customer experience over transactional support.', marks: ['strong'] }],
              },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'capabilities',
            sectionTitle: 'Key Capabilities',
            backgroundColor: 'dark',
            columns: 2,
            features: [
              { icon: '👤', title: 'Customer-Centered Platform', description: 'All interactions organized by customer, not tickets' },
              { icon: '🤖', title: 'AI-Powered Resolution and Support', description: 'Automate resolutions while assisting human agents' },
              { icon: '⚡', title: 'Real-Time Customer Context', description: 'Complete conversation and purchase history instantly available' },
              { icon: '🔄', title: 'Omnichannel Continuity', description: 'Seamless experience across all communication channels' },
              { icon: '🛒', title: 'Commerce Integration', description: 'Direct integration with order management and catalogs' },
              { icon: '🔒', title: 'Trusted Access & Configuration', description: 'Secure, compliant access to customer intelligence' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'quick-links-sales',
            anchorId: 'quick-links-sales',
            sectionTitle: 'Quick Links For Sales',
            backgroundColor: 'white',
            columns: 2,
            features: [
              { icon: '🎬', title: 'Launch video', description: 'Product launch overview and announcement' },
              { icon: '📹', title: 'Customer AI Video', description: 'Detailed product walkthrough and capabilities' },
              { icon: '📄', title: 'Customer AI one-pager', description: 'Quick reference sheet for sales conversations' },
              { icon: '📚', title: 'New customer stories', description: 'Latest customer success stories and testimonials' },
              { icon: '📷', title: 'Cluadia photos', description: 'Visual assets and brand imagery' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'quick-links-csam',
            anchorId: 'quick-links-csam',
            sectionTitle: 'Quick Links For CS/AM',
            backgroundColor: 'gray',
            columns: 2,
            features: [
              { icon: '📊', title: 'Sidekick Sales usage', description: 'Usage guidelines and best practices' },
              { icon: '🚀', title: 'Rollout to Customers for CSMs', description: 'Customer rollout strategy and materials' },
              { icon: '📦', title: 'New customer assets', description: 'Latest onboarding and training materials' },
              { icon: '🎥', title: 'Claudia videos', description: 'Video resources for customer presentations' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'videos',
            anchorId: 'videos',
            sectionTitle: 'Customer AI Videos',
            backgroundColor: 'white',
            columns: 2,
            features: [
              { icon: '👋', title: 'Gladly Demo Walk', description: 'Complete platform demonstration' },
              { icon: '🎉', title: 'Gladly Launch Video', description: 'Official product launch announcement' },
              { icon: '🤖', title: 'Customer AI Video', description: 'Deep dive into AI capabilities' },
              { icon: '📝', title: 'Gladly AI Video w/ text', description: 'Captioned version for accessibility' },
              { icon: '🔧', title: 'Customer AI Videos w/ tec', description: 'Technical deep-dive versions' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'shareable',
            anchorId: 'shareable',
            sectionTitle: 'Shareable Content',
            backgroundColor: 'gray',
            columns: 2,
            features: [
              { icon: '📄', title: 'Gladly One Pager', description: 'One-page overview for quick reference' },
              { icon: '🤖', title: 'Customer AI One Pager', description: 'AI-focused one-page summary' },
              { icon: '🎨', title: 'External Customer Branded', description: 'Branded materials for customer-facing use' },
              { icon: '📖', title: 'Buyer\'s Guide or XLSX site', description: 'Comprehensive buyer\'s guide and resources' },
              { icon: '✉️', title: 'Email to Gladly on AI ...', description: 'Email templates for AI discussions' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'pr',
            anchorId: 'pr',
            sectionTitle: 'PR',
            backgroundColor: 'white',
            columns: 3,
            features: [
              { icon: '📰', title: 'WIRED article', description: 'Featured coverage in WIRED magazine' },
              { icon: '💼', title: 'Fortune Access', description: 'Fortune magazine feature and analysis' },
              { icon: '📢', title: 'Further News', description: 'Additional press coverage and mentions' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'enablement',
            anchorId: 'enablement',
            sectionTitle: 'Enablement',
            backgroundColor: 'gray',
            columns: 2,
            features: [
              { icon: '🎓', title: 'Customer AI Nametrix Training', description: 'Training session on AI capabilities' },
              { icon: '💬', title: 'Connection of the Message to the', description: 'Messaging framework and guidelines' },
              { icon: '❓', title: 'Rebranding FAQ', description: 'Frequently asked questions about rebrand' },
              { icon: '🔗', title: 'Sidekick AI Demo Integrations', description: 'Demo integration guides and examples' },
              { icon: '🚀', title: '2025 GKO', description: 'Go-to-market kickoff materials' },
            ],
          },
          {
            _type: 'ctaSection',
            _key: 'cta',
            heading: 'Need Help With Customer AI?',
            subheading: 'Can\'t find what you\'re looking for? Reach out to the enablement team',
            primaryCtaText: 'Ask in #enablement-resources',
            primaryCtaLink: '#',
            secondaryCtaText: 'Browse All Products',
            secondaryCtaLink: '/product',
            backgroundColor: 'purple',
          },
        ],
      },
      {
        _type: 'page',
        _id: 'page-product-guides-journeys',
        title: 'Guides and Journeys',
        slug: { _type: 'slug', current: 'guides-and-journeys' },
        quickNav: [{ label: 'Overview', anchor: 'overview' }],
        pageBuilder: [
          {
            _type: 'heroSection',
            _key: 'hero',
            badge: 'GUIDES AND JOURNEYS',
            heading: 'Guides and Journeys',
            subheading: 'Workflow automation for support teams',
            layout: 'centered',
            backgroundColor: 'purple',
          },
        ],
      },
      {
        _type: 'page',
        _id: 'page-product-app-platform',
        title: 'App Platform',
        slug: { _type: 'slug', current: 'app-platform' },
        quickNav: [
          { label: 'What it is', anchor: 'what-it-is' },
          { label: 'Available Apps', anchor: 'available-apps' },
          { label: 'Talk Tracks + Next Steps', anchor: 'talk-tracks' },
          { label: 'Content', anchor: 'content' },
          { label: 'Demo', anchor: 'demo' },
          { label: 'Technical Enablement', anchor: 'technical-enablement' },
          { label: 'Revenue Enablement', anchor: 'revenue-enablement' },
        ],
        pageBuilder: [
          {
            _type: 'heroSection',
            _key: 'hero',
            badge: 'APP PLATFORM',
            heading: 'App Platform',
            subheading: 'Gladly\'s App Platform is a low-code integration layer that connects external systems like order management, loyalty, and payment directly to Gladly\'s interface for agents and AI. Teams get faster setup, better service outcomes, and lower IT overhead.',
            layout: 'centered',
            primaryCtaText: 'Learn More',
            primaryCtaLink: '#what-it-is',
            secondaryCtaText: 'View Resources',
            secondaryCtaLink: '#content',
            backgroundColor: 'green',
          },
          {
            _type: 'contentSection',
            _key: 'what-it-is',
            anchorId: 'what-it-is',
            sectionTitle: 'What it is',
            backgroundColor: 'dark',
            includeLaunchStatus: true,
            launchStatus: {
              heading: '🚀 Launch Status',
              statusItems: [
                { label: 'Initial research', isActive: false },
                { label: 'Added to roadmap', isActive: false },
                { label: 'Discovery and design', isActive: false },
                { label: 'Build in progress', isActive: false },
                { label: 'Prototyping', isActive: false },
                { label: 'Limited rollout', isActive: false },
                { label: 'Broader rollout', isActive: false },
                { label: '➡️ Open Access 🎉 ⬅️', isActive: true },
              ],
              description: 'App Platform is generally available and accessible to all customers.',
            },
            content: [
              {
                _key: 'block-1',
                _type: 'block',
                children: [{ _key: 'span-1', _type: 'span', text: 'Gladly\'s App Platform is a low-code integration layer that connects external systems like order management, loyalty, and payment directly to Gladly\'s interface for agents and AI.' }],
              },
              {
                _key: 'block-2',
                _type: 'block',
                children: [{ _key: 'span-2', _type: 'span', text: 'Why it matters: It eliminates tool-switching, gives agents full context, and lets AI act on real data—teams get faster setup, better service outcomes, and lower IT overhead.', marks: ['strong'] }],
              },
              {
                _key: 'block-3',
                _type: 'block',
                children: [{ _key: 'span-3', _type: 'span', text: 'Who it\'s for: For IT and CX teams at ecommerce and high-tech customers who rely on multiple systems to support customers and need simple tools to unify data across agents and AI.', marks: ['strong'] }],
              },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'capabilities',
            sectionTitle: 'Key Capabilities',
            backgroundColor: 'dark',
            columns: 2,
            features: [
              { icon: '🔄', title: 'Bi-directional data sync (read and write)', description: 'Two-way data flow between Gladly and external systems' },
              { icon: '⚡', title: 'Real-time visibility in Hero and Sidekick', description: 'Live data accessible to both human agents and AI' },
              { icon: '🔗', title: '40+ pre-built integrations', description: 'Ready-to-use connections with popular business tools' },
              { icon: '🛠️', title: 'Open APIs and SDK', description: 'Build custom integrations for unique requirements' },
              { icon: '🔒', title: 'Secure and compliant', description: 'Enterprise-grade security and data protection' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'available-apps',
            anchorId: 'available-apps',
            sectionTitle: 'Available Apps',
            backgroundColor: 'white',
            columns: 1,
            features: [
              { icon: '📱', title: 'List of available apps', description: 'Browse all pre-built integrations and apps available on the platform' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'talk-tracks',
            anchorId: 'talk-tracks',
            sectionTitle: 'Talk Tracks + Next Steps',
            backgroundColor: 'gray',
            columns: 2,
            features: [
              { icon: '🏢', title: 'Next steps - Internal', description: 'Internal process and handoff documentation' },
              { icon: '🤝', title: 'Next steps - External', description: 'Customer-facing implementation steps' },
              { icon: '💬', title: 'SC + CRM Talk Tracks', description: 'Solutions consulting and CRM conversation guides' },
              { icon: '💼', title: 'AE Talk Tracks', description: 'Account executive conversation frameworks' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'content',
            anchorId: 'content',
            sectionTitle: 'Content',
            backgroundColor: 'white',
            columns: 3,
            features: [
              { icon: '📄', title: '📄 START | Apps Platform 3...', description: 'Getting started guide for App Platform' },
              { icon: '📊', title: 'Templated Slides', description: 'Pre-built presentation templates' },
              { icon: '🗺️', title: 'September Roadmap Deck', description: 'Product roadmap and upcoming features' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'demo',
            anchorId: 'demo',
            sectionTitle: 'Demo',
            backgroundColor: 'gray',
            columns: 1,
            features: [
              { icon: '🎬', title: 'How to set up an App', description: 'Step-by-step demo of app configuration and setup' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'technical-enablement',
            anchorId: 'technical-enablement',
            sectionTitle: 'Technical Enablement',
            backgroundColor: 'white',
            columns: 3,
            features: [
              { icon: '🎓', title: 'Product Enablement - ...', description: 'Technical product training materials' },
              { icon: '📚', title: 'Product Enablement - ...', description: 'Advanced technical enablement' },
              { icon: '🏗️', title: 'App Platform Technical En...', description: 'Platform architecture and technical overview' },
              { icon: '👨‍💻', title: 'App Platform Technical En...', description: 'Developer documentation and API guides' },
              { icon: '🦸', title: 'App Platform for Hero Tech...', description: 'Hero integration technical guide' },
              { icon: '⚙️', title: 'App Platform for Hero Tech...', description: 'Advanced Hero platform configurations' },
            ],
          },
          {
            _type: 'featureGridSection',
            _key: 'revenue-enablement',
            anchorId: 'revenue-enablement',
            sectionTitle: 'Revenue Enablement',
            backgroundColor: 'gray',
            columns: 2,
            features: [
              { icon: '📧', title: 'Sidekick Email + ...', description: 'Revenue enablement for Email integrations' },
              { icon: '📅', title: '12/19/24: App Platform &...', description: 'Platform enablement session recording' },
              { icon: '📂', title: 'Session Folder', description: 'Complete enablement session materials' },
            ],
          },
          {
            _type: 'ctaSection',
            _key: 'cta',
            heading: 'Need Help With App Platform?',
            subheading: 'Can\'t find what you\'re looking for? Reach out to the enablement team',
            primaryCtaText: 'Ask in #enablement-resources',
            primaryCtaLink: '#',
            secondaryCtaText: 'Browse All Products',
            secondaryCtaLink: '/product',
            backgroundColor: 'purple',
          },
        ],
      },
    ];

    const results = [];
    for (const product of products) {
      const result = await adminClient.createOrReplace(product);
      results.push(result.title);
      console.log(`Created: ${product.title}`);
    }

    return NextResponse.json({
      success: true,
      message: `Cleaned up duplicates and created ${results.length} products`,
      products: results
    });
  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json(
      { success: false, error: String(error) },
      { status: 500 }
    );
  }
}
