import { adminClient } from '@/lib/sanity-admin';
import { NextResponse } from 'next/server';

const trainingSessions = [
  // October 2025
  {
    _id: 'training-1',
    _type: 'trainingSession',
    title: 'Technical Buyer Enablement (CIO/CTO)',
    date: '2025-10-16T10:00:00Z',
    dateDisplay: 'Oct 2025',
    product: 'all',
    productLabel: 'Persona',
    description: 'Technical Buyer (CIO/CTO)',
    duration: '60 min',
    materials: 'Recording + Deck',
    dateFilter: '30days',
    link: 'https://drive.google.com/drive/folders/1nbfFUgTi095VsfX3AmmzmuaSYzQocC_6',
    tags: ['Persona', 'Sales Skills'],
  },
  // September 2025
  {
    _id: 'training-2',
    _type: 'trainingSession',
    title: 'Sidekick Sales Launch Enablement',
    date: '2025-09-26T10:00:00Z',
    dateDisplay: 'Sept 2025',
    product: 'sidekick-sales',
    productLabel: 'Product',
    description: 'Comprehensive launch training for Sidekick Sales',
    duration: '60 min',
    materials: 'Recording + Deck',
    dateFilter: '90days',
    link: 'https://drive.google.com/drive/folders/13Py0_Jo_W0hPjBmuvoSvASzoGAuY76JB',
    tags: ['Product', 'GTM Strategy'],
  },
  // August 2025
  {
    _id: 'training-3',
    _type: 'trainingSession',
    title: 'Sidekick Standalone Land Grab',
    date: '2025-08-28T10:00:00Z',
    dateDisplay: 'August 2025',
    product: 'sidekick-standalone',
    productLabel: 'GTM Strategy',
    description: 'Strategies for rapid Standalone adoption and market penetration',
    duration: '50 min',
    materials: 'Recording + Deck',
    dateFilter: '90days',
    link: 'https://drive.google.com/drive/folders/1iHvQKRgV62igGJOs78hiLFqWeJ7pQADb',
    tags: ['GTM Strategy'],
  },
  {
    _id: 'training-4',
    _type: 'trainingSession',
    title: 'Sales Activity Expectations & SK Voice AMA',
    date: '2025-08-21T10:00:00Z',
    dateDisplay: 'August 2025',
    product: 'sidekick-voice',
    productLabel: 'Product',
    description: 'Sales activity tracking expectations and Sidekick Voice Q&A',
    duration: '55 min',
    materials: 'Recording + Demo',
    dateFilter: '90days',
    link: 'https://drive.google.com/drive/folders/1E2AScNwdHcEPceLLijcPVbMV3ur4CoV9',
    tags: ['Product', 'Team'],
  },
  {
    _id: 'training-5',
    _type: 'trainingSession',
    title: 'SimpleSat Partnership Enablement',
    date: '2025-08-14T10:00:00Z',
    dateDisplay: 'August 2025',
    product: 'all',
    productLabel: 'Partner',
    description: 'Partnership enablement for SimpleSat integration',
    duration: '40 min',
    materials: 'Recording + Deck',
    dateFilter: '90days',
    link: 'https://drive.google.com/drive/folders/1nzLYQOMUioW4tN6N9qb2KuCxKyjxp6G0',
    tags: ['Partner'],
  },
  // July 2025
  {
    _id: 'training-6',
    _type: 'trainingSession',
    title: 'BVA SLA + Live Demo Walkthrough',
    date: '2025-07-24T10:00:00Z',
    dateDisplay: 'July 2025',
    product: 'all',
    productLabel: 'Demo',
    description: 'New BVA Slack workflow + Walkthrough of the new demo',
    duration: '60 min',
    materials: 'Recording + Deck',
    dateFilter: 'earlier',
    link: 'https://drive.google.com/drive/folders/1ln1XqawDwxRGg9o1AvjVKfTemyKNc_hb',
    tags: ['Demo', 'Team'],
  },
  // June 2025
  {
    _id: 'training-7',
    _type: 'trainingSession',
    title: 'Sidekick for Zendesk',
    date: '2025-06-26T10:00:00Z',
    dateDisplay: 'June 2025',
    product: 'all',
    productLabel: 'Product',
    description: 'Set up, capabilities, channels, and optimization. Deal Spotlight: Express',
    duration: '50 min',
    materials: 'Recording + Deck',
    dateFilter: 'earlier',
    link: 'https://drive.google.com/drive/folders/1IFwYsGN6lGSNfrY_djYE9Ad8laPVAQZv',
    tags: ['Product'],
  },
  {
    _id: 'training-8',
    _type: 'trainingSession',
    title: 'SK for Email + App Platform',
    date: '2025-06-18T10:00:00Z',
    dateDisplay: 'June 2025',
    product: 'sidekick-email',
    productLabel: 'Product',
    description: 'Foundational enablement for Sidekick on email + App Platform refresher by AE and SC leadership',
    duration: '55 min',
    materials: 'Recording + Deck',
    dateFilter: 'earlier',
    link: 'https://drive.google.com/drive/folders/1u8rrVzUyw3uhc7Ih5U8wodF_HI7mDXu8',
    tags: ['Product'],
  },
  {
    _id: 'training-9',
    _type: 'trainingSession',
    title: 'Selling High + FM Deck',
    date: '2025-06-12T10:00:00Z',
    dateDisplay: 'June 2025',
    product: 'all',
    productLabel: 'Sales Skills',
    description: 'Selling high to drive strategic growth + First meeting deck template expectations',
    duration: '45 min',
    materials: 'Recording + Deck',
    dateFilter: 'earlier',
    link: 'https://docs.google.com/presentation/d/11LraGLfKuVWTg2IpB302i4W3XhA6rbsoW799J5HSvYY/edit?slide=id.g36081577ae8_0_0#slide=id.g36081577ae8_0_0',
    tags: ['Sales Skills', 'GTM Strategy'],
  },
  // May 2025
  {
    _id: 'training-10',
    _type: 'trainingSession',
    title: 'Gladly 2.0 Demo Update',
    date: '2025-05-29T10:00:00Z',
    dateDisplay: 'May 2025',
    product: 'all',
    productLabel: 'Demo',
    description: 'What has changed, what is available, & live walkthrough',
    duration: '55 min',
    materials: 'Recording + Demo',
    dateFilter: 'earlier',
    link: 'https://drive.google.com/drive/folders/1tGOFiMF8NgNBwH3wkekzntw4PoYXSILq',
    tags: ['Demo', 'Product', 'Sales Skills'],
  },
  {
    _id: 'training-11',
    _type: 'trainingSession',
    title: 'Customer AI Narrative',
    date: '2025-05-22T10:00:00Z',
    dateDisplay: 'May 2025',
    product: 'customer-ai',
    productLabel: 'Value Selling',
    description: 'Deep dive into Gladly\'s messaging, what has changed, and why it matters',
    duration: '50 min',
    materials: 'Recording + Deck',
    dateFilter: 'earlier',
    link: 'https://drive.google.com/drive/folders/1EnCiS-ms5rBJPjKTRwYNaKHd3deiyr7w',
    tags: ['Product', 'Value Selling'],
  },
  {
    _id: 'training-12',
    _type: 'trainingSession',
    title: 'Sidekick Standalone Tactical Enablement',
    date: '2025-05-08T10:00:00Z',
    dateDisplay: 'May 2025',
    product: 'sidekick-standalone',
    productLabel: 'Sales Skills',
    description: 'DQ, discovery, objection, integration training for Sidekick Standalone',
    duration: '55 min',
    materials: 'Recording + Deck',
    dateFilter: 'earlier',
    link: 'https://drive.google.com/drive/folders/1t5F7F5nUg9aEewVTgKXoynn7IC3goro2',
    tags: ['Sales Skills', 'Product'],
  },
  {
    _id: 'training-13',
    _type: 'trainingSession',
    title: 'Sidekick Standalone + Sidekick Sales',
    date: '2025-05-01T10:00:00Z',
    dateDisplay: 'May 2025',
    product: 'sidekick-sales',
    productLabel: 'Product',
    description: 'Foundational trainings for Sidekick Standalone and Sidekick Sales',
    duration: '60 min',
    materials: 'Recording + Deck',
    dateFilter: 'earlier',
    link: 'https://drive.google.com/drive/folders/1MGcyQeRUqXHwbwvN8o0pRDf2x3haT4ww',
    tags: ['Product'],
  },
  // April 2025
  {
    _id: 'training-14',
    _type: 'trainingSession',
    title: 'Sidekick Voice: Demo, Pitch, Value',
    date: '2025-04-10T10:00:00Z',
    dateDisplay: 'April 2025',
    product: 'sidekick-voice',
    productLabel: 'Demo',
    description: 'New Demo in Generic Retail, SK Voice pitch overview, BVA and ROI calc updates',
    duration: '50 min',
    materials: 'Recording + Demo',
    dateFilter: 'earlier',
    link: 'https://drive.google.com/drive/folders/1P1Z25foeBQxtPVwlhWDbpw-euL-esQT9',
    tags: ['Demo', 'Value Selling', 'Product'],
  },
  // March 2025
  {
    _id: 'training-15',
    _type: 'trainingSession',
    title: 'Assembled Partner Enablement',
    date: '2025-03-13T10:00:00Z',
    dateDisplay: 'March 2025',
    product: 'all',
    productLabel: 'Partner',
    description: 'Partnership enablement for Assembled integration',
    duration: '40 min',
    materials: 'Recording + Deck',
    dateFilter: 'earlier',
    link: 'https://drive.google.com/drive/folders/1M_Ohrw71Bh1sRAp_AR5VvvRom-yVpxsj',
    tags: ['Partner'],
  },
  // January 2025
  {
    _id: 'training-16',
    _type: 'trainingSession',
    title: 'Guides and Journeys',
    date: '2025-01-16T10:00:00Z',
    dateDisplay: 'January 2025',
    product: 'all',
    productLabel: 'Product',
    description: 'Intro to the value of Guides and Journeys and how they work',
    duration: '40 min',
    materials: 'Recording + Guide',
    dateFilter: 'earlier',
    link: 'https://drive.google.com/drive/folders/1-kn6fk6oeoTH3UEFqI9QB7VXYUe31cjr',
    tags: ['Product'],
  },
  {
    _id: 'training-17',
    _type: 'trainingSession',
    title: 'Voice AI',
    date: '2025-01-09T10:00:00Z',
    dateDisplay: 'January 2025',
    product: 'sidekick-voice',
    productLabel: 'Product',
    description: 'Intro to Gladly\'s vision for Voice AI and how it works',
    duration: '50 min',
    materials: 'Recording + Deck',
    dateFilter: 'earlier',
    link: 'https://drive.google.com/drive/folders/1UnroMHkh611miuBExAy-3EcNx1aCDSrr',
    tags: ['Product'],
  },
  // December 2024
  {
    _id: 'training-18',
    _type: 'trainingSession',
    title: 'App Platform + Loop Returns',
    date: '2024-12-19T10:00:00Z',
    dateDisplay: 'December 2024',
    product: 'hero',
    productLabel: 'Partner',
    description: 'Customer facing App Platform value slides + partnership value of Loop',
    duration: '55 min',
    materials: 'Recording + Deck',
    dateFilter: 'earlier',
    link: 'https://drive.google.com/drive/folders/1S1hZ31LvK2E6ob6hcYiOWW9yyTkmY3Mn',
    tags: ['Partner', 'Product'],
  },
  {
    _id: 'training-19',
    _type: 'trainingSession',
    title: 'CS Sidekick ROI Calculator',
    date: '2024-12-01T10:00:00Z',
    dateDisplay: 'December 2024',
    product: 'all',
    productLabel: 'Value Selling',
    description: 'Customer Success Sidekick ROI Calculator training and resources',
    duration: '45 min',
    materials: 'Recording + Calculator',
    dateFilter: 'earlier',
    link: 'https://drive.google.com/drive/folders/1ac3fuUAoOJshUU7u2BQplnC8cwKvpZlt',
    tags: ['Value Selling'],
  },
  {
    _id: 'training-20',
    _type: 'trainingSession',
    title: 'BVA Calculator Refresh',
    date: '2024-11-15T10:00:00Z',
    dateDisplay: 'November 2024',
    product: 'all',
    productLabel: 'Value Selling',
    description: 'Updated BVA Calculator training and resources',
    duration: '45 min',
    materials: 'Recording + Calculator',
    dateFilter: 'earlier',
    link: 'https://drive.google.com/drive/folders/1IT1H1wQDGpdMGp0R4oNpqQwPJ2bU9-DT',
    tags: ['Value Selling'],
  },
];

export async function GET() {
  try {
    if (!process.env.SANITY_API_TOKEN) {
      return NextResponse.json(
        { error: 'Missing SANITY_API_TOKEN in environment variables' },
        { status: 500 }
      );
    }

    // First, delete all existing training sessions
    const existingSessions = await adminClient.fetch('*[_type == "trainingSession"]._id');
    for (const id of existingSessions) {
      await adminClient.delete(id);
    }

    // Then create the new ones with isActive: true
    const results = [];
    for (const session of trainingSessions) {
      const result = await adminClient.create({ ...session, isActive: true });
      results.push(result._id);
    }

    return NextResponse.json({
      success: true,
      message: `Successfully seeded ${results.length} training sessions!`,
      sessions: results,
    });
  } catch (error: any) {
    console.error('Error seeding training sessions:', error);
    return NextResponse.json(
      { error: error.message, details: error },
      { status: 500 }
    );
  }
}
